CREATE USER C##usuario3 IDENTIFIED BY "12345";
ALTER USER C##usuario3 ACCOUNT UNLOCK;
GRANT CREATE SESSION TO C##usuario3;
GRANT CONNECT, RESOURCE TO C##usuario3;
ALTER USER C##usuario3 QUOTA UNLIMITED ON USERS;

/**********************************************************/

SELECT SYS_CONTEXT ('USERENV', 'CON_NAME') FROM dual;
SHOW CON_NAME;
SHOW PDBS;

ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER simples 
IDENTIFIED BY 12345 
DEFAULT TABLESPACE users 
QUOTA 10M ON users 
TEMPORARY TABLESPACE temp
QUOTA 5M ON system;

GRANT CREATE SESSION,
CREATE TABLE,
CREATE SEQUENCE,
CREATE VIEW,
CREATE PROCEDURE
TO simples;


