CREATE USER C##usuario2 IDENTIFIED BY "12345";
ALTER USER C##usuario2 ACCOUNT UNLOCK;
GRANT CREATE SESSION TO C##usuario2;
GRANT CONNECT, RESOURCE TO C##usuario2;
ALTER USER C##usuario2 QUOTA UNLIMITED ON USERS;

/**********************************************************/

SELECT SYS_CONTEXT ('USERENV', 'CON_NAME') FROM dual;
SHOW CON_NAME;
SHOW PDBS;

ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER simples 
IDENTIFIED BY 12345 
DEFAULT TABLESPACE users 
QUOTA 10M ON users 
TEMPORARY TABLESPACE temp
QUOTA 5M ON system;

GRANT CREATE SESSION,
CREATE TABLE,
CREATE SEQUENCE,
CREATE VIEW,
CREATE PROCEDURE
TO simples;


